apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-portfolio-app
  labels:
    app: devops-portfolio-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devops-portfolio-app
  template:
    metadata:
      labels:
        app: devops-portfolio-app
    spec:
      containers:
        - name: web
          image: REPLACE_WITH_ACR/devops-app:latest
          ports:
            - containerPort: 5000
          readinessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 20